name: refresh map

on:
  push:
    branches: ["master"]

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests

      - name: Execute Python script
        run: |
          python main.py

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a || echo "No changes to commit"
          git push https://$TOKEN@github.com/mhmmdlsubasi/RecordAnalyze.git master
