name: Fetch MGM Data

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodule
        run: git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Alt modülün gereksinimlerini yükle

      - name: Fetch MGM data
        run: |
          python main.py  # Alt modüldeki MGM veri çekme betiğini çalıştır

      - name: Save results
        run: |
          mkdir -p results
          mv veriler.csv results/mgm_data_$(date +"%Y-%m-%d").csv  # Veri dosyasını results dizinine taşı

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add MGM data for $(date +'%Y-%m-%d')"
          git push
